version: "3.9"

# 2022/01/02 K. Chinzei
# See ./.env
#
# The MIT License (MIT)
# Copyright (c) Kiyo Chinzei (kchinzei@gmail.com)
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

services:
  db:
    # platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      TZ: "Asia/Tokyo"

    
  wordpress:
    depends_on:
      - db
    # platform: linux/x86_64
    image: wordpress:latest
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      - ./data/wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      TZ: "Asia/Tokyo"

  wordmove:
    image: welaika/wordmove
    tty: true
    depends_on:
      - wordpress
    # container_name: "${PRODUCTION_NAME}_wm"
    volumes:
      - ./config:/html
      - ./data/wordpress:/var/www/html
    environment:
      LOCAL_SERVER_PORT: "${WORDPRESS_PORT}"
      LOCAL_DB_NAME: "${MYSQL_DATABASE}"
      LOCAL_DB_USER: "${MYSQL_USER}"
      LOCAL_DB_PASSWORD: "${MYSQL_PASSWORD}"
      LOCAL_DB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      LOCAL_DB_HOST: "db"
      LOCAL_DB_PORT: 3306

      PRODUCTION_URL: "${PRODUCTION_URL}"
      PRODUCTION_DIR_PATH: "${PRODUCTION_DIR_PATH}"
      PRODUCTION_DB_NAME: "${PRODUCTION_DB_NAME}"
      PRODUCTION_DB_USER: "${PRODUCTION_DB_USER}"
      PRODUCTION_DB_PASSWORD: "${PRODUCTION_DB_PASSWORD}"
      PRODUCTION_DB_HOST: "${PRODUCTION_DB_HOST}"
      PRODUCTION_DB_PORT: ${PRODUCTION_DB_PORT}
      PRODUCTION_FTP_HOST: "${PRODUCTION_FTP_HOST}"
      PRODUCTION_FTP_USER: "${PRODUCTION_FTP_USER}"
      PRODUCTION_FTP_PASSWORD: "${PRODUCTION_FTP_PASSWORD}"
      PRODUCTION_FTP_PORT: ${PRODUCTION_FTP_PORT}
    # To access this ssh,
    #   docker exec -it (container name of wordmove) /bin/bash
    # Container name of wordmove should look like
    # ${PRODUCTION_NAME}_wordmove_1, where (${PRODUCTION_NAME} is in .env file)
    # You can find it when you run 'docker-compose up -d'.

#volumes:
#  db_data:
